added Diagram document type to + button
owncloud/richdocuments pull request #436
Opened 2021-12-14 11:30 UTC by merttumer

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

2021-12-14 16:44 UTC, jnweiger requested changes
Please redirect this PR to the release-2.7.0 branch for inclusion in the 2.7.0 release.
We'll merge into master when released.

2021-12-15 08:29 UTC, JammingBen approved these changes

2021-12-16 18:01 UTC, jnweiger approved these changes

2021-12-16 18:02 UTC, merged

2022-01-25 17:20 UTC, mrow4a commented
@jnweiger needs merge to muster, currently it is only on release branch