Zotero fixes for 4.1.0rc
owncloud/richdocuments pull request #529
Opened 2023-11-09 14:48 UTC by mrow4a

Fixes: 
- https://github.com/owncloud/richdocuments/issues/527
- https://github.com/owncloud/richdocuments/issues/528

Screenshot for new input handling
<img width="980" alt="Screenshot 2023-11-09 at 15 46 41" src="https://github.com/owncloud/richdocuments/assets/13368647/85d24b1f-7e32-4ed6-9418-57b21866b4ae">

2023-11-09 17:47 UTC, jnweiger requested changes
#528 is fixed here. Thanks.
But I am not 100% happy with the fix for #527

There is no message, when no key was entered, but there is a message when a correct key was entered. See https://github.com/owncloud/richdocuments/issues/527#issuecomment-1804266520

2023-11-10 07:19 UTC, mrow4a commented
@jnweiger added note that 22.05.10 is required in admin settings

2023-11-10 07:54 UTC, jvillafanez commented
> Update the existing key or save empty to delete

Just checking, is it true? Maybe I'm wrong, but if the value is empty, I think it will keep the current value or set an empty string (which I don't know how it will behave)

> There is no message, when no key was entered, but there is a message when a correct key was entered.

I agree there should be some message. I think it's fixed, but I haven't tested it.


Code looks good to me.

2023-11-13 09:19 UTC, mrow4a commented
@jnweiger could you rereview ? the adjustments are there.

2023-12-01 12:50 UTC, jnweiger requested changes
Found the missing bit to fix the annoying "Zotero API key is incorrect" message.
Suggestion added.

Everthing else save button wit copy paste, etc, works fine now!

2023-12-01 13:09 UTC, mrow4a commented on lib/Controller/WopiController.php
> +			$userPrivateInfo['ZoteroAPIKey'] = $zoteroAPIPrivateKey;
ok! now I finally know where your problem resided originaly! Ahhh good catch!

2023-12-01 13:09 UTC, mrow4a commented on lib/Controller/WopiController.php
> +			$userPrivateInfo['ZoteroAPIKey'] = $zoteroAPIPrivateKey;
I will fix it otherwise

2023-12-01 13:20 UTC, mrow4a commented
@jnweiger fixed your very good catch with empty key

2023-12-01 14:12 UTC, jnweiger approved these changes
Looks like we finally solved all the issues here !

Thanks @mrow4a !

2023-12-01 14:14 UTC, merged